# Generated by Django 4.2.17 on 2025-01-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='analytics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_analytics', to='blog_app.postanalytics'),
        ),
        migrations.AlterField(
            model_name='postanalytics',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_analytics', to='blog_app.post'),
        ),
    ]
