# Generated by Django 4.2.17 on 2025-01-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_customuser_bio_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalytics',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_posts', to='blog_app.user'),
        ),
    ]
