# Generated by Django 4.2.17 on 2025-01-27 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_postanalytics_viewed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanalytics',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
